import Navbar from "./component/navbar/navbar";
import 'bootstrap/dist/css/bootstrap.css';
import "./main.css";
import Link from "next/link";

export const metadata = {
  title: "LoftApart Szczyrk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <footer>
          <p style={{fontSize: "10px"}}>Wykonanie <a href={"https://github.com/MichalKrokosz"} target="_blank" >Michał Krokoszyński</a></p>
        </footer>
      </body>
    </html>
  );
}
